### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ellentkoch** [UBC-MDS/DSCI532_Group107_JobAnalyzer#27]
I really enjoyed exploring your app, great work! Here is my feedback:

**Mechanics:** Overall mechanics look great, team members are communicating through issues, using pull requests, and commit messages are informative.

**App:** Your app looks great! All of the plots chosen were effective at showing your data. I particularly liked the heatmap combined with the bar chart of men vs. women in the first tab. The descriptions at the top of each tab are helpful in showing the user how to navigate the app. Here are a few suggestions:
- It’s not clear what this data represents. Is it for the whole world, or a specific country? It would be good to have a sentence or two at the top describing the entire app, in addition to the descriptions you’ve provided for each tab. 
- Make sure it’s clear that the years are 10-year averages (eg. 1850-1859) rather than just that year (1850). In the plots, when you hover over the plots, the tooltip just shows the single year (1850). 
- In the 1st tab, there is an error with the tool tip on the bar plot, where it shows sex twice. 
- For the third tab, it says that the tooltip will show the “actual percentage” but the tooltip instead shows the total number of men or women with that job.

**Reflection:** Great job with the reflection. I like that it is organized into sections, and that you clearly addressed feedback that you had received from TAs and peers. Overall, awesome work!
@EitharAlfatih @SimardeepKaur @Margaret8521

**Comment by EitharAlfatih** [comment]
Thanks, Ellen. We considered all the points you mentioned in your feedback and we added a reflection on them in the reflection.md file.
